### ISSUE TITLE
Grass isn't rendered in certain camera positions and angles

### ISSUE THREAD

**Issue by hichemfantar** [isaac-mason/sketches#374]
I've been able to reproduce the same bug present in pmndrs grass shader example.
https://sketches.isaacmason.com/sketch/nature/grass

https://github.com/user-attachments/assets/d51b47b7-de6c-45e8-b674-645ba11053db

related to https://github.com/pmndrs/examples/issues/81

**Comment by isaac-mason** [comment]
The grass geometry likely just needs a bounding sphere set :)

**Comment by isaac-mason** [comment]
see: https://github.com/isaac-mason/sketches/commit/215c0ae5e63d37d39e8027b26c224459664c939d#diff-e8adae55929edd1c8c844ba9c3fbcfd1d42fbca85c36fbbdb9d790b3d56f66e1R272

**Comment by hichemfantar** [comment]
@isaac-mason i think it's fixed!
do you know how i could apply a similar fix to the [pmndrs grass example](https://github.com/pmndrs/examples/issues/81)?

**Comment by isaac-mason** [comment]
I've raised a PR in pmndrs/examples :)
